# ---------------------------------------------------------
# CCB WORKSHOP: Hands-On AI Survival Analysis (SOLUTIONS)
# ---------------------------------------------------------

# Load necessary libraries
library(dplyr)
library(survival)
library(survminer)

# Load the clinical trial data
df <- read.csv("../data/tcga_clinical_trial.csv")


# ________________________________________________________
# PHASE 1: Setting Lab Rules (Tool: /create-instructions)
# ________________________________________________________

# (Completed via Chat. Generates a .github/instructions/ file applying
# tidyverse and survminer rules to the workspace.)


# ____________________________________________
# PHASE 2: Data Exploration (Tool: Chat Mode)
# ____________________________________________

# Chat Response Example:
# Column names: patient_id, age_at_diagnosis, clinical_stage, biomarker_status,
#               treatment_arm, os_days, vital_status.
# Unique values in biomarker_status: "BRAF_V600E", "Wildtype".
# Unique values in treatment_arm: "Standard_Chemo", "Targeted_Therapy".


# ___________________________________________
# PHASE 3: Data Wrangling (Tool: Agent Mode)
# ___________________________________________

clean_df <- df |>
  dplyr::filter(!is.na(os_days)) |>
  dplyr::mutate(
    os_months = os_days / 30.4,
    status_binary = ifelse(vital_status == "Dead", 1, 0)
  )


# __________________________________________________
# PHASE 4: Kaplan-Meier Plotting (Tool: Agent Mode)
# __________________________________________________

km_fit <- survfit(
  Surv(os_months, status_binary) ~ treatment_arm,
  data = clean_df
)

km_plot <- ggsurvplot(
  km_fit,
  data = clean_df,
  pval = TRUE,
  risk.table = TRUE,
  title = "Overall Survival by Treatment Arm",
  xlab = "Time (Months)",
  ylab = "Survival Probability",
  theme = theme_minimal()
)

# Create figures directory if it doesn't exist, then save plot
dir.create("figures", showWarnings = FALSE)
pdf("figures/survival_plot.pdf", width = 8, height = 6)
print(km_plot)
dev.off()


# ______________________________________________________
# PHASE 5: AI Debugging (Tool: Terminal Auto-Detection)
# ______________________________________________________

# THE FIX: Copilot will automatically read the terminal error, identify that
# `cleen_dataframe` is misspelled, and correct it to `clean_df`.

cox_model <- coxph(
  Surv(os_months, status_binary) ~ treatment_arm + clinical_stage,
  data = clean_df
)

summary(cox_model)


# _________________________________________________________
# PHASE 6: Stratified Survival Analysis (The Secret Math!)
# _________________________________________________________

km_stratified <- survfit(
  Surv(os_months, status_binary) ~ treatment_arm + biomarker_status,
  data = clean_df
)

stratified_plot <- ggsurvplot(
  km_stratified,
  data = clean_df,
  pval = TRUE,
  risk.table = TRUE,
  risk.table.height = 0.4,
  legend = "right",
  title = "Survival by Treatment and Biomarker",
  xlab = "Time (Months)",
  ylab = "Survival Probability",
  theme = theme_minimal()
)

dir.create("figures", showWarnings = FALSE)
pdf("figures/stratified_plot.pdf", width = 10, height = 8)
print(stratified_plot)
dev.off()


# ____________________________________________________
# PHASE 7: Build a Custom Agent (Tool: /create-agent)
# ____________________________________________________

# (Completed via the interactive /create-agent wizard in the Chat panel)


# ____________________________________________
# PHASE 8: Python Translation & File Creation
# ____________________________________________

# Resulting Python code generated by @python-translator in
# hands-on/clean_data.py:
#
# import pandas as pd
# import numpy as np
#
# clean_df = df.dropna(subset=['os_days']).copy()
# clean_df['os_months'] = clean_df['os_days'] / 30.4  # nolint
# clean_df['status_binary'] = np.where(  # nolint
#   clean_df['vital_status'] == 'Dead', 1, 0)


# _________________________________________________
# PHASE 9: The Magic Commit (Tool: Source Control)
# _________________________________________________

# (Completed in the VS Code Source Control GUI)
