# ---------------------------------------------------------
# CCB WORKSHOP: Hands-On AI Survival Analysis (SOLUTIONS)
# ---------------------------------------------------------

# Load necessary libraries
library(dplyr)
library(survival)
library(survminer)

# Load the clinical trial data
df <- read.csv("data/tcga_clinical_trial.csv")


# ________________________________________________
# PHASE 1: Data Exploration (Tool: Sidebar Chat)
# ________________________________________________

# Chat Response Example:
# The dataset contains 500 rows and 7 columns.
# Column names: patient_id, age_at_diagnosis, clinical_stage, biomarker_status, 
#               treatment_arm, os_days, vital_status.
# Unique values in biomarker_status: "BRAF_V600E", "Wildtype".
# Unique values in treatment_arm: "Standard_Chemo", "Targeted_Therapy".


# _____________________________________________________
# PHASE 2: Data Wrangling (Tool: Inline Chat / Ctrl+I)
# _____________________________________________________

clean_df <- df %>%
  filter(!is.na(os_days)) %>%
  mutate(
    os_months = os_days / 30.4,
    status_binary = ifelse(vital_status == "Dead", 1, 0)
  )


# ___________________________________________________________
# PHASE 3: Legacy Code Interpretation (Tool: Slash Commands)
# ___________________________________________________________

#' Calculate Cumulative Hazard (Nelson-Aalen Estimator)
#'
#' This function computes the cumulative hazard function using the 
#' Nelson-Aalen estimator for right-censored survival data.
#'
#' @param t A numeric vector of survival times.
#' @param e A numeric vector of event indicators (1 for event, 0 for censored).
#'
#' @return A numeric vector of cumulative hazards corresponding to the sorted times.
#' @export
calculate_risk_metric <- function(t, e) {
  if(length(t) != length(e)) stop("Mismatch")
  o <- order(t)
  t <- t[o]; e <- e[o]
  r <- length(t):1
  h <- e/r
  return(cumsum(h))
}


# __________________________________________________________
# PHASE 4: Kaplan-Meier Plotting (Tool: Verbose Prompting)
# __________________________________________________________

km_fit <- survfit(Surv(os_months, status_binary) ~ treatment_arm, data = clean_df)

ggsurvplot(
  km_fit,
  data = clean_df,
  pval = TRUE,
  risk.table = TRUE,
  title = "Overall Survival by Treatment Arm",
  xlab = "Time (Months)",
  ylab = "Survival Probability",
  theme = theme_minimal()
)


# _______________________________________________________
# PHASE 5: AI Debugging (Tool: #terminal or Error Chat)
# _______________________________________________________

# THE FIX: Copilot will identify that `cleen_dataframe` is misspelled and 
# correct it to `clean_df`.

cox_model <- coxph(Surv(os_months, status_binary) ~ treatment_arm + clinical_stage, 
                   data = clean_df)

summary(cox_model)


# __________________________________________________
# PHASE 6: The Magic Commit (Tool: Source Control)
# __________________________________________________

# (Completed in the VS Code Source Control GUI)


# _____________
# BONUS PHASES 
# _____________

# BONUS 1: The Math (Interaction Terms)
cox_interaction <- coxph(Surv(os_months, status_binary) ~ treatment_arm * biomarker_status, 
                         data = clean_df)

ggforest(cox_interaction, data = clean_df)


# BONUS 2: Python Translation & File Creation
# Resulting Python code generated by the Chat/Agent in a new file:
#
# import pandas as pd
# import numpy as np
# 
# clean_df = df.dropna(subset=['os_days']).copy()
# clean_df['os_months'] = clean_df['os_days'] / 30.4
# clean_df['status_binary'] = np.where(clean_df['vital_status'] == 'Dead', 1, 0)